name: Build project and deploy to SmarterASP.NET

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build package and deploy to SmarterASP.NET
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display current directory (for debugging)
        run: pwd

      - name: Display files in repository (for debugging)
        run: dir

      - name: Publish .NET Core Application
        run: |
          cd RentBuySell  # Change this to your actual project folder
          dotnet publish RentBuySell.csproj -c Release -o ../published_app

      - name: Display published files (for debugging)
        run: dotnet publish RentBuySell/RentBuySell.csproj -c Release -o published_app

      - name: Stop the web server (restart the website)
        run: |
          echo "Stopping the web server..."
          # Run an FTP command to stop the web server or restart the site (if available)
          # SmarterASP.NET doesn't support direct "stop server" FTP commands but can be restarted through MSDeploy
          # Alternatively, use an API or control panel if available
          curl -u "krishnareddi1254-001:${{ secrets.FTP_PASSWORD }}" -X POST "ftp://win1022.site4now.net:21/stop_web_server"

      - name: Sync files to SmarterASP.NET
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win1022.site4now.net
          username: krishnareddi1254-001
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: published_app/
          server-dir: /wwwroot/

      - name: Start the web server (restart the website)
        run: |
          echo "Starting the web server..."
          # Run an FTP command or MSDeploy command to start the web server
          curl -u "krishnareddi1254-001:${{ secrets.FTP_PASSWORD }}" -X POST "ftp://win1022.site4now.net:21/start_web_server"

